# CI for ADF validation and exporting an ARM Template to deploy

variables:
 - group: CICD_VARIABLES
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - ADF/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Validate_stage
  displayName: Validate_stage
  jobs:
    - job: ARM_Validation
      displayName: 'ARM Template Validation and Deployment'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: ../../preliminary-steps.yml
          parameters:
            cicdChain: 'CI'
            infoPath: 'info.yaml'
            env: 'ADFPRD'
## Keyvault
        - task: AzureKeyVault@1
          displayName: 'Azure Dev KeyVault'
          inputs:
            azureSubscription: 'ACS_Food_Solution_Dev_SPN'
            KeyVaultName: 'bnlwe-fr01-p-56626-kv-01'

## replace valuse
        - task: cmdLine@2
          displayName: 'Replace values'
          inputs:
            script: |
              sed -i "s/PASSWORD/$(PRDSSISPASSWORD)/" $(System.DefaultWorkingDirectory)/ADF/integrationRuntime/*.json
              sed -i "s/USERNAME/$(PRDSSISUSERNAME)/" $(System.DefaultWorkingDirectory)/ADF/integrationRuntime/*.json
# Installs Node and the npm packages
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
   
        - task: Npm@1
          inputs:
            command: 'install'
            workingDir: '$(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm'
            verbose: true
          displayName: 'Install npm package'

# Validates all of the Data Factory resources in the repository.
        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm'
            customCommand: 'run build validate  $(System.DefaultWorkingDirectory)/ADF /subscriptions/$(azureSubscription)/resourceGroups/$(prdresgroup)/providers/Microsoft.DataFactory/factories/$(DataFactoryName)'
          displayName: 'Validate' 
          
# Validate and Generate ARM Template. 
        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm'
            customCommand: 'run build export $(System.DefaultWorkingDirectory)/ADF /subscriptions/$(azureSubscription)/resourceGroups/$(prdresgroup)/providers/Microsoft.DataFactory/factories/$(DataFactoryName) "ArmTemplate"'
          displayName: 'Validate and Generate ARM template' 

## Replace the value of the Newly created ARM Template
        - task: cmdLine@2
          displayName: 'Replace values'
          inputs:
            script: |
              sed -i 's/bnlwe-fr01-d-56690-pa01-adf-01/bnlwe-fr01-p-56626-pa01-adf-01/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/Frontier-FS-SSISIR-Dev/Frontier-FS-SSISIR-PRD/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/bnlwe-fr01-d-56690-pa01-sql-dev-01/bnlwe-fr01-p-56626-pa01-sql-prd-01/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/UNLDevAdmin/UNLPAdmin/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/prod-226.westeurope/prod-14.westeurope/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/1a8d4cf2400c487c8ee3e8ad97aa311b/36df4bfa05104adb94b6a9037a748a84/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/X1LiF6yNGaMCXNYGbAgB2m5snppcR9cv6ucs6Ew5o9w/i6Upq60s6INo-82iBxXJ34eFVt88buvKQ1K3C6EhLj4/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/prod-229.westeurope/prod-93.westeurope/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/df91498921e443328548d891fae7d6f0/a1bdd03d490b4b26adda1866e7dcd21f/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/mhhdvI7Jr8ZVU6A0MqPc4mQmt00tY6O6GqMDOwFc_zI/KCHMmzOmHbCkHZDGJDfMslx29kf9ZR5W6HxkpUZI-ks/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/prod-136.westeurope/prod-188.westeurope/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/a7697c853e0b4a6584311a0f09642945/3d32a18235354534938f3871cdb48398/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/e3t3FtLDcFXzFCLTUweIcMr-PKCRpg6Z1E7ZNudoSek/0qEqpsL9g5at0nI8jQzymfyVVwGC6eY_ty5P4Zj2Nng/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/Standard_D2_v3/Standard_D8_v3/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/DWConnectionStrings/DWPRDConnectionStrings/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/LogConnectionStrings/LogPRDConnectionStrings/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/STGConnectionStrings/STGPRDConnectionStrings/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/DEVBlob/PRDBlob/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i 's/bnlwe-fr01-n-56690-kv-02.vault.azure.net/bnlwe-fr01-p-56626-kv-01.vault.azure.net/' $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i "s/SFTPPASS/$(PRDSFTPPASSWORD)/" $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i "s/PASSWORD/$(PRDSSISPASSWORD)/" $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i "s/USERNAME/$(PRDSSISUSERNAME)/" $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i "s/BLACKSMITHHOST/$(PRDBLACKSMITHHOST)/g" $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i "s/BLACKSMITHPORT/$(PRDBLACKSMITHPORT)/g" $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i "s/BLACKSMITHUSER/$(PRDBLACKSMITHUSER)/g" $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/*.json
              sed -i "s/\Stage\/Inbound/Production\/Inbound/" $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/ARMTemplateForFactory.json
# ADF Deployment
        - task: AzureResourceGroupDeployment@2
          displayName: 'Data Factory Dev ARM Deploy'
          inputs:
           azureSubscription: ACS_Food_Solution_Dev_SPN
           resourceGroupName: $(prdresgroup)
           location: $(dataFactory_location)
           csmFile: $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/ARMTemplateForFactory.json
           csmParametersFile: $(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/ARMTemplateParametersForFactory.json
           deploymentMode: Incremental
           deploymentName: '$(DataFactoryName)'

# TAG RESOURCES
        - task: AzureCLI@2
          displayName: 'Tagging ADF on Azure Cloud'
          continueOnError: false
          inputs:
           azureSubscription: 'ACS_Food_Solution_Dev_SPN'
           scriptLocation: 'inlineScript'
           scriptType: 'bash'
           inlineScript: |
              set -euovx pipefail
              echo -e "\e[1mWriting resource tag on Azure\e[0m"
              az tag create \
              --resource-id /subscriptions/$(azureSubscription)/resourceGroups/$(prdresgroup)/providers/Microsoft.DataFactory/factories/$(DataFactoryName) \
              --tags version=$(newVersion)

# Zipping files

        - task: ArchiveFiles@2
          continueOnError: false
          displayName: 'Artifact Creation'
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Deployment/YAML/ADF/npm/ArmTemplate/'
            archiveType: zip
            includeRootFolder: false
            archiveFile: '$(System.DefaultWorkingDirectory)/$(arfname).zip'

        - publish: $(System.DefaultWorkingDirectory)/$(arfname).zip
          displayName: 'Publish artifact'
          artifact: ARMTemplate