# CI-CD for SSIS

trigger:
  branches:
    include:
    - development
  paths:
    include:
    - SSIS/*

pool:
  vmImage: 'windows-latest'
  
stages:
- stage: Build
  displayName: Validate_stage
  jobs:
    - job: SSIS_Build_Deploy
      displayName: 'SSIS Compilation'
      steps:

## Keyvault
        - task: AzureKeyVault@1
          displayName: 'Azure Dev KeyVault'
          inputs:
            azureSubscription: 'ACS_Food_Solution_Dev_SPN'
            KeyVaultName: 'bnlwe-fr01-n-56690-kv-02'

## Replace the Values
        - task: cmdLine@2
          displayName: 'Replace values'
          inputs:
            script: |
              sed -i "s/USERNAME/$(DEVSSISUSERNAME)/" $(System.DefaultWorkingDirectory)/SSIS/*.conmgr
              sed -i "s/PASSWORD/$(DEVSSISPASSWORD)/" $(System.DefaultWorkingDirectory)/SSIS/*.conmgr
              sed -i -e "s|DEVBlob|$(DEVBlob)|g" $(System.DefaultWorkingDirectory)/SSIS/UFS_Blob.conmgr
        - task: SSISBuild@1
          displayName: 'SSIS Compilation'
          inputs:
           projectPath: '$(System.DefaultWorkingDirectory)/SSIS/UFS_ETL.dtproj'
           outputPath: '$(Build.ArtifactStagingDirectory)/SSISBuild'

        - task: ArchiveFiles@2
          displayName: 'Archive Files'
          inputs:
            rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/SSISBuild'
            includeRootFolder: true
            archiveType: zip
            archiveFile: '$(System.DefaultWorkingDirectory)/SSISPackage.zip'
            replaceExistingArchive: true

        - publish: $(System.DefaultWorkingDirectory)/SSISPackage.zip
          displayName: 'Publish artifact'
          artifact: SSISPackage
        - publish: $(System.DefaultWorkingDirectory)/SSIS/
          displayName: 'Publish artifact'
          artifact: SSISPackage Files
## Deploy SSIS 
        - task: SSISDeploy@1
          displayName: 'SSIS Deploy'
          inputs:
            sourcePath: '$(Build.ArtifactStagingDirectory)/SSISBuild'
            destinationType: ssisdb
            destinationServer: '$(ssissrv)'
            destinationPath: '/SSISDB/UFS/UFS_ETL'
            authType: sql
            username: '$(DEVSSISUSERNAME)'
            password: '$(DEVSSISPASSWORD)'

#################
- stage: Archive
  dependsOn: Build
  jobs:
    - job: DownloadArtifact
      displayName: 'Download Artifact'
      pool: 
       vmImage: 'ubuntu-latest'
      steps:
       - template: ../../preliminary-steps.yml
         parameters:
            cicdChain: 'CI'
            infoPath: 'info.yaml'
            env: 'SSISDEV'

## TAG RESOURCES
       - task: AzureCLI@2
         displayName: 'Tagging SSIS on Azure Cloud'
         continueOnError: false
         inputs:
           azureSubscription: 'ACS_Food_Solution_Dev_SPN'
           scriptLocation: 'inlineScript'
           scriptType: 'bash'
           inlineScript: |
              set -euovx pipefail
              echo -e "\e[1mWriting resource tag on Azure\e[0m"
              az tag create \
              --resource-id /subscriptions/$(azureSubscription)/resourceGroups/$(resgroup)/providers/Microsoft.Sql/servers/$(ssisserver) \
              --tags version=$(newVersion)