# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - develop
    - QA
    - master
  paths:
    include:
    - APIs/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: CICD_variables

steps:
  - ${{if eq( variables['Build.SourceBranch'], 'refs/heads/feature/develop' )}}:
            - task: CmdLine@2
              continueOnError: false
              displayName: "Install FunctionApp Libraries"
              inputs:
                  script: |
                    python -m pip install --upgrade pip
                    if [[ -f $(System.DefaultWorkingDirectory)/APIs/requirements.txt ]]; then
                        python -m pip install --target="$(System.DefaultWorkingDirectory)/.python_packages/lib/site-packages" -r $(System.DefaultWorkingDirectory)/APIs/requirements.txt
                    fi

            - task: CmdLine@2
              continueOnError: false
              displayName: "Creating artifact"
              inputs:
                script: |
                  mkdir $(System.DefaultWorkingDirectory)/package-functionapp
                  cp -Rf $(System.DefaultWorkingDirectory)/APIs/* package-functionapp
                  cp -Rf $(System.DefaultWorkingDirectory)/.python_packages/ package-functionapp
                  cd $(System.DefaultWorkingDirectory)/package-functionapp
                  zip -r functionapp.zip .
                  cd ..
                 
            - task: AzureCLI@2
              continueOnError: false
              displayName: 'Azure CLI to deploy FunctionApp' 
              inputs:
                azureSubscription: $(devservicename)
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  #az functionapp config appsettings set --name '$(devfunapp)' --resource-group '$(devrg)' --settings "Dummy=1234"
                  az functionapp deployment source config-zip --resource-group '$(devrg)' --name '$(devfunapp)' --src '$(System.DefaultWorkingDirectory)/package-functionapp/functionapp.zip'

## QA Deployment
  - ${{if eq( variables['Build.SourceBranch'], 'refs/heads/feature/QA' )}}:
            - task: CmdLine@2
              continueOnError: false
              displayName: "Install FunctionApp Libraries"
              inputs:
                  script: |
                    python -m pip install --upgrade pip
                    if [[ -f $(System.DefaultWorkingDirectory)/APIs/requirements.txt ]]; then
                        python -m pip install --target="$(System.DefaultWorkingDirectory)/.python_packages/lib/site-packages" -r $(System.DefaultWorkingDirectory)/APIs/requirements.txt
                    fi

            - task: CmdLine@2
              continueOnError: false
              displayName: "Creating artifact"
              inputs:
                script: |
                  mkdir $(System.DefaultWorkingDirectory)/package-functionapp
                  cp -Rf $(System.DefaultWorkingDirectory)/APIs/* package-functionapp
                  cp -Rf $(System.DefaultWorkingDirectory)/.python_packages/ package-functionapp
                  cd $(System.DefaultWorkingDirectory)/package-functionapp
                  zip -r functionapp.zip .
                  cd ..
                 
            - task: AzureCLI@2
              continueOnError: false
              displayName: 'Azure CLI to deploy FunctionApp' 
              inputs:
                azureSubscription: $(qaservicename)
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  #az functionapp config appsettings set --name '$(qafunapp)' --resource-group '$(devrg)' --settings "Dummy=1234"
                  az functionapp deployment source config-zip --resource-group '$(qarg)' --name '$(qafunapp)' --src '$(System.DefaultWorkingDirectory)/package-functionapp/functionapp.zip'

## Prod Deployment
  - ${{if eq( variables['Build.SourceBranch'], 'refs/heads/feature/master' )}}:
            - task: CmdLine@2
              continueOnError: false
              displayName: "Install FunctionApp Libraries"
              inputs:
                  script: |
                    python -m pip install --upgrade pip
                    if [[ -f $(System.DefaultWorkingDirectory)/APIs/requirements.txt ]]; then
                        python -m pip install --target="$(System.DefaultWorkingDirectory)/.python_packages/lib/site-packages" -r $(System.DefaultWorkingDirectory)/APIs/requirements.txt
                    fi

            - task: CmdLine@2
              continueOnError: false
              displayName: "Creating artifact"
              inputs:
                script: |
                  mkdir $(System.DefaultWorkingDirectory)/package-functionapp
                  cp -Rf $(System.DefaultWorkingDirectory)/APIs/* package-functionapp
                  cp -Rf $(System.DefaultWorkingDirectory)/.python_packages/ package-functionapp
                  cd $(System.DefaultWorkingDirectory)/package-functionapp
                  zip -r functionapp.zip .
                  cd ..
                 
            - task: AzureCLI@2
              continueOnError: false
              displayName: 'Azure CLI to deploy FunctionApp' 
              inputs:
                azureSubscription: $(prodservicename)
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  #az functionapp config appsettings set --name '$(prodfunapp)' --resource-group '$(devrg)' --settings "Dummy=1234"
                  az functionapp deployment source config-zip --resource-group '$(prodrg)' --name '$(prodfunapp)' --src '$(System.DefaultWorkingDirectory)/package-functionapp/functionapp.zip'