# DevOps CI  Pipeline
variables:
 - group: CICD_VARIABLES

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Database/UFS_STG/*

stages:
- stage: Build
  displayName: Build
  jobs:

  - job: Build
    displayName: Build
    timeoutInMinutes: 20
    pool:
      vmImage: 'windows-latest'
      demands:
      - msbuild
      - sqlpackage
    steps:
## Keyvault
     - task: AzureKeyVault@1
       displayName: 'Azure Dev KeyVault'
       inputs:
        azureSubscription: 'ACS_Food_Solution_Dev_SPN'
        KeyVaultName: 'bnlwe-fr01-p-56626-kv-01'

 ## Compilation for UFS_STG
     - task: MSBuild@1
       displayName: 'MS Build'
       inputs:
        solution: $(System.DefaultWorkingDirectory)/Database/UFS_STG/*.sqlproj

## Archive for UFS_STG
     - task: ArchiveFiles@2
       inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Database/UFS_STG/bin/Debug/UFS_STG.dacpac'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(System.DefaultWorkingDirectory)/STG.zip'
        replaceExistingArchive: true

## STG Publish              
     - publish: $(System.DefaultWorkingDirectory)/STG.zip
       displayName: 'Publish dacpac'
       artifact: 'UFS_STG'

## Deploy STG
     - task: SqlAzureDacpacDeployment@1
       displayName: 'Azure SQL STG Dacpac Task'
       inputs:
         azureSubscription: ACS_Food_Solution_Dev_SPN
         ServerName: 'bnlwe-fr01-p-56626-pa01-sql-prd-01.database.windows.net'
         DatabaseName: 'bnlwe-fr01-p-56626-pa01-sqldb-prd-03'
         SqlUsername: $(PRDSSISUSERNAME)
         SqlPassword: $(PRDSSISPASSWORD)
         DacpacFile: $(System.DefaultWorkingDirectory)/Database/UFS_STG/bin/Debug/UFS_STG.dacpac

#################
- stage: Archive
  dependsOn: Build
  jobs:
    - job: DownloadArtifact
      displayName: 'Download Artifact'
      pool: 
       vmImage: 'ubuntu-latest'
      steps:
       - template: ../../preliminary-steps.yml
         parameters:
            cicdChain: 'CI'
            infoPath: 'info.yaml'
            env: 'SQLSTGPRD'

 ## TAG Resources               
       - task: AzureCLI@2
         displayName: 'Tagging SQL DB on Azure Cloud'
         continueOnError: false
         inputs:
            azureSubscription: 'ACS_Food_Solution_Dev_SPN'
            scriptLocation: 'inlineScript'
            scriptType: 'bash'
            inlineScript: |
              set -euovx pipefail
              echo -e "\e[1mWriting resource tag on Azure\e[0m"
              az tag create \
              --resource-id /subscriptions/$(azureSubscription)/resourceGroups/$(prdresgroup)/providers/Microsoft.Sql/servers/$(prdsqlserver)/databases/$(dbname) \
              --tags version=$(newVersion)

## Applying TAG to a repo
       - task: CmdLine@2
         displayName: 'TAG REPO'
         env: 
           SYSTEM_ACCESSTOKEN: $(System.AccessToken)
         inputs:
            script: |
              git remote set-url origin https://$(CICD_PAT)@$(Repository)
              commitAuthorName=$(git log --format='%an' $(Build.SourceVersion)^!)
              commitAuthorEmail=$(git log --format='%ae' $(Build.SourceVersion)^!)
              git config user.email "$commitAuthorEmail"
              git config user.name "$commitAuthorName"
              git tag -a $(arfname)_$(newVersion) -m "$(newVersion)"
              git push origin --tags